### ISSUE TITLE
Should be an option not to remove scheme on autolinked/self-linked URLs

### ISSUE THREAD

**Issue by adam-iris** [textile/python-textile#16]
When ```auto_link=True```, or when self-linking a URL like ```"$":http://www.example.com/``` the scheme (```http://```) is removed from the displayed link.

I realize this follows the PHP version, but looking at the history behind that change (https://github.com/textile/php-textile/issues/48#issuecomment-4176459) it looks like something tossed in without much discussion.  I (and several people I showed this to) feel like this was a bad decision, as it makes it less clear that the given text is actually a URL.  It seems like there should at least be an option to turn this off.

Ironically, the one case where I think it _should_ be removed is for ```mailto:``` links, but it's not.  (This does deviate from the PHP version, which removes them.)

**Comment by ikirudennis** [comment]
I see your point about stripping the scheme from the URL being unclear.  However, I'm trying to match the functionality of the php version as much as possible.  There are some issues with how it handles links.  Hopefully it will contribute to cleaner code for us.
I've resolved the issue with `mailto:` links displaying incorrectly.  It will be merged in soon-ish.

**Comment by netcarver** [comment]
I just pushed an experimental branch to php-textile that allows control of the output of URI schemes in textile self-links.

Ref: https://github.com/textile/php-textile/compare/self-link-scheme-visibility-control

Looking forward to your issue report @ikirudennis so I can see if this ties it up.
