### ISSUE TITLE
Autolink should ignore urls within image references

### ISSUE THREAD

**Issue by ahaith** [textile/python-textile#17]
e.g. 
    `!http://www.ox.ac.uk/favicon.ico!`
becomes the non-functioning
`<img src="<a href="http: www.ox.ac.uk favicon.ico" rel="nofollow"">"www.ox.ac.uk/favicon.ico" />`

**Comment by ikirudennis** [comment]
This is resolved in the develop branch.  It will be merged in soon-ish.
