### ISSUE TITLE
"caps" are not replaced correctly

### ISSUE THREAD

**Issue by kevinmgrant** [textile/python-textile#18]
The last version I used was PyTextile 2.1.4, which did not try to replace caps.  Now in version 2.2.2, unexpected HTML conversions occur for text that contains capital letters.

For example, the text "`CFString`" in a textile file becomes "`<span class="caps">CFS</span>tring`" in HTML, and "`TCP/IP`" becomes "`<span class="caps">TCP</span>/IP`".

My preference is to have a way to disable this substitution entirely because it is not necessary.  Still, the regular expressions could be improved by scanning text beyond an all-caps range; for instance, require all-caps ranges to be immediately followed by spaces or punctuation, and certainly not lowercase letters.

**Comment by hhsprings** [comment]
It seems [redcloth](http://redcloth.org/try-redcloth/) has the same problem for the latter case (`TCP/IP`).  I also believe this case must be render as `<span class="caps">TCP/IP</span>` (and of cource `CFString` must not be recognized as caps). But neither [redcloth spec](https://github.com/jgarber/redcloth/blob/master/spec/fixtures/textism.yml) nor [textile-spec](https://github.com/textile/textile-spec) don't explain these behaviours well.

**Comment by ikirudennis** [comment]
Yeah, I see this as more of a problem for the spec than it is a problem with this project's implementation.  I'd rather keep this consistent with the official version even if it is obviously wrong here.

**Comment by appli-intramuros** [comment]
How can we disable the fact that caps are replaced by a span ?

**Comment by ikirudennis** [comment]
That's pretty easy to accomplish (if not immediately obvious):

    no_span = textile.Textile()
    no_span.glyph_replace[-1] = r'\1{0}:glyph:\2\3'.format(self.uid)
    c.parse('text TEXT text')

That ought to output `'\t<p>text TEXT text</p>'`. I hope that helps.

**Comment by appli-intramuros** [comment]
@ikirudennis it works perfectly. Thanks !
