### ISSUE TITLE
Double encoding of code blocks

### ISSUE THREAD

**Issue by csomme** [textile/python-textile#21]
When using the texttile_restricted function, data in code blocks is double encoded. With a document like the following:

```
h1. xml example

bc. 
<foo>
  bar
</foo>
```

I would expect it to output to look something like:
```
<h1>xml example</h1>

<pre><code>
&lt;foo&gt;
  bar
&lt;/foo&gt;
</pre></code>
```

Instead, it's generating something like:
```
<h1>xml example</h1>

<pre><code>
&amp;lt;foo&amp;gt;
  bar
&amp;lt;/foo&amp;gt;
```

**Comment by ikirudennis** [comment]
This is resolved in the develop branch. It will be merged in soon-ish.
