### ISSUE TITLE
Markup not parsed if followed by certain characters

### ISSUE THREAD

**Issue by sangel10** [textile/python-textile#22]
I am using textile in a project using legacy data ported over form a Rails project that was using the Redcloth textile gem.

We have a number of text formatted like this that it seems textile is unable to parse:

`_(artist-name)Ty Segall_’s`

the expected output would be 

`<em class="artist-name">Ty Segall</em>’s `

however textile.textile returns the raw string:

`_(artist-name)Ty Segall_’s`

Is there a way to configure textile so that it will parse text that is formatted this way (i.e. without whitespace after the closing underscore)?

**Comment by ikirudennis** [comment]
This works as expected in the develop branch.  There's no need for the change in the pull request.
