### ISSUE TITLE
Tables don't output thead

### ISSUE THREAD

**Issue by jimktrains** [textile/python-textile#31]
Table headers are not wrapped in a thead tag. Libraries such as [DataTables.net](https://datatables.net/) require a thead section.  Additionally, it is a more proper and semantic way of formatting a table.

    >>> import textile
     >>> a = """
     ... |_. header|
     ... |row 1|
     ... """
     >>> print(textile.textile(a))
     	<table>
     		<tr>
     			<th>header</th>
     		</tr>
     		<tr>
     			<td>row 1</td>
     		</tr>
     	</table>

expected output would be:

     	<table>
     		<thead>
     			<tr>
     				<th>header</th>
     			</tr>
     		</thead>
     		<tbody>
     			<tr>
     				<td>row 1</td>
     			</tr>
     		<tbody>
     	</table>

version

     % pip3 show textile
     ---
     Metadata-Version: 2.0
     Name: textile
     Version: 2.3.3

**Comment by ikirudennis** [comment]
Hi, there's actually a [special syntax](https://txstyle.org/doc/15/tables) for this functionality.  I believe the following should get you what you're looking for:

    |^.
    |_. header|
    |-.
    |row 1|

It produces:

      <table>
        <thead>
                <tr>
                        <th>header</th>
                </tr>
        </thead>
        <tbody>
                <tr>
                        <td>row 1</td>
                </tr>
        </tbody>
        </table>

Does that fit your use case?

**Comment by jimktrains** [comment]
Yes it does! Somehow I've never seen the |^ in the docs! Thanks!
