### ISSUE TITLE
using sys.exectuable instead of hardcoded 'python' in test command

### ISSUE THREAD

**Issue by arunpersaud** [textile/python-textile#38]
in  tests/test_cli.py line 5

'python' is used inside a command, but for python3 installation, e.g. on openSUSE, this doesn't work, since python would be the 2.7 version. Perhaps sys.executable should be used here?

I ran into this issue while trying to package textile for openSUSE as a python3 package, not sure, if this is also used in other locations.

Arun

**Comment by sebix** [comment]
> I ran into this issue while trying to package textile for openSUSE as a python3 package, not sure, if this is also used in other locations.

It's already there: https://build.opensuse.org/package/show/devel:languages:python3/python3-textile

**Comment by ikirudennis** [comment]
Is there any action required on my end?  Is there anything I could or should do to simplify things?

**Comment by arunpersaud** [comment]
@sebix: I know;) I'm part of devel:languages:python3 and working on updating the version in dlp3 to 2.3.6. 
see https://build.opensuse.org/package/show/home:apersaud:branches:devel:languages:python3/python3-textile

**Comment by sebix** [comment]
I can push a fix, but this won't solve the problem. The textile module is not installed in standard paths in the build environment, so we can only import textile from the current directory, not the installed lib. This will work, but that's not the aim of the test.

**Comment by sebix** [comment]
In the build environment we can just remove this test I think.

Concerning the package for opensuse: I'm waiting for the singlespec of pytest, then I can finalize the singlespec package for textile.

**Comment by ikirudennis** [comment]
Thanks once again, @sebix. This will be pushed to master and released soon-ish.
