### ISSUE TITLE
Incorrect wrap pre-froematted value

### ISSUE THREAD

**Issue by tynopet** [textile/python-textile#47]
I try to format this value:
```
pre.. word

another

word

yet anothe word
```
but get the incorrect output with excess pre tags:
```
<pre><pre>&lt;pre&gt;&lt;pre&gt;word\n\nanother&lt;/pre&gt;\n\nword&lt;/pre&gt;\n\nyet anothe word</pre></pre>
```
[screen](http://imgur.com/a/P0xll)

How to fix it?

**Comment by ikirudennis** [comment]
This is the same sort of situation as with #45. If you need a more urgent fix, you can use `pip install git+https://github.com/textile/python-textile.git@a74bcebb7d6a2618fccf712e81cb1c0d0eabda22#egg=textile` to install a version with a fix for both this issue and #45.
Thanks for reporting these issues.

**Comment by tynopet** [comment]
Thank you very much!

**Comment by tynopet** [comment]
Hello, I fetch you fixes and found this bug:
```
p. text text


h1. Hello
```
Rendered textile:
```
<p>text text</p>


h1. Hello
```
If I write two new lines after element, textile not processing next tag.

**Comment by ikirudennis** [comment]
Thanks for providing this update. It's very helpful in improving textile.

**Comment by tynopet** [comment]
Thank you for fixes.
