### ISSUE TITLE
Incorrect wrap code with Java generics in pre

### ISSUE THREAD

**Issue by tynopet** [textile/python-textile#50]
Hello, I tried to wrap next code in `pre..`:

```
public class Tynopet<T extends Framework> {}

final List<List<String>> multipleList = new ArrayList<>();
```

and get the output:
```
public class Tynopet&lt;T extends Framework&gt; {}

final List<list<string>&gt; multipleList = new ArrayList&lt;&gt;();</list<string>
```

How to fix this? Thank you

**Comment by ikirudennis** [comment]
@tynopet, firstly, thanks so much for these bug reports. I have a question for you. I can create a new release and upload it to pypi, but if you have more bugs to report, we might end up at version number 2.3.52368 before long. Do you foresee uncovering more bugs like this? You've been on a real tear recently, and I appreciate it very much. I just want to try to balance solving issues and not releasing a new version every other day.

By the way, do you mind telling me how you're finding these bugs?

In the meantime, as always, you can update to the latest fix with `pip install git+https://github.com/textile/python-textile.git@develop#egg=textile`

Thanks again!

**Comment by tynopet** [comment]
Hello, @ikirudennis , I work junior web developer in a company [StackSoft](https://onyma.ru/), and we use textile as the main text editor. Our testers and developers find this issues, and I report you. Thanks for fast fixes them. While this is all known to our problems. Sorry for my bad English.
