### ISSUE TITLE
Encoding issue with img alt/title 

### ISSUE THREAD

**Issue by jeroenp** [textile/python-textile#58]
I have a similar issue to #30, still on python 2.7: With an image tag, the tostringlist still fails. 

Not sure how or why the A tag works for me, but the image doesn't. 

Added test and a fix in https://github.com/jeroenp/python-textile/commit/a6a2b9a520db14c9b7bf73f219967226078d9d02

**Comment by ikirudennis** [comment]
Curse you, Python 2.6!
