### ISSUE TITLE
Missing files in the source tarball.

### ISSUE THREAD

**Issue by thmo** [textile/python-textile#60]
The 3.0.0 tar file misses a bunch of files, some of which I'd consider important.

Comparing the 2.3.16 and the 3.0.0 tar files, these files are missing:
```
.coveragerc
CHANGELOG.textile
CONTRIBUTORS.txt
LICENSE.txt
README.textile
pytest.ini
requirements.txt
tests/test_attributes.py
tests/test_block.py
tests/test_cli.py
tests/test_footnoteRef.py
tests/test_getRefs.py
tests/test_getimagesize.py
tests/test_github_issues.py
tests/test_glyphs.py
tests/test_image.py
tests/test_imagesize.py
tests/test_lists.py
tests/test_retrieve.py
tests/test_span.py
tests/test_subclassing.py
tests/test_table.py
tests/test_textile.py
tests/test_textilefactory.py
tests/test_urls.py
tests/test_utils.py
tests/test_values.py
```

**Comment by thmo** [comment]
And like in #59, the files are in the tarball when I run a `python ./setup.py sdist` locally in my checkout...

**Comment by ikirudennis** [comment]
I uploaded a tarball yesterday that seems like it has everything you're looking for. Which source tarball are you using?

**Comment by thmo** [comment]
Ah, ok, using the `-withtests` variant has indeed all the files, thanks. I thought the only difference were the test files.
