### ISSUE TITLE
Restricted mode and CSS attribute parsing

### ISSUE THREAD

**Issue by brondsem** [textile/python-textile#65]
Since version 2.3.0, style attributes like `h2{position:absolute;top:200px}. This is a title` started to come through into the output when using `textile_restricted`. In 2.2.2 and earlier, `textile_restricted` kept those out.

Is there a way in the latest versions to omit style attributes from being rendered?

**Comment by brondsem** [comment]
I ran a git bisect on this and found the regression began in ae31b8a73b88abdddfbff31ba1c3de32c7c3f0fa  I may work on a pull request to restore the style attribute restrictions, although it looks like it will involve passing the `restricted` flag into `parse_attributes` in a lot of places.  Any thoughts?

**Comment by brondsem** [comment]
I've created pull request #67 for this

**Comment by ikirudennis** [comment]
Fixed by #67. Thanks once more, @brondsem
