### ISSUE TITLE
Integration with tabulate

### ISSUE THREAD

**Issue by kaki4am** [textile/python-textile#66]
Dear team, 

I am trying to run textile on top of tabulate (https://pypi.org/project/tabulate/)? In my case, I have weird behaviours as the tabulate tables are not shaped correctly, especially with the tabulate style "grid". Potentially something to look at!

Thank you, Nicolas

**Comment by ikirudennis** [comment]
I haven't looked at a possible solution yet, but I do have a couple thoughts:

- Is there a reason not to use the tabulate style "textile?"
- Can you provide an example snippet of code or textile to test against?
- You might be able to get away with some combination of `notextile` tags to exclude the table and then run tabulate after?

Thanks!

**Comment by kaki4am** [comment]
Hi Dennis, thank for your response. I have totally missed the "textile" tabulate style. It indeed works like a charm.
