### ISSUE TITLE
Does the spec allow for lists inside endnotes?

### ISSUE THREAD

**Issue by AB1908** [textile/python-textile#79]
> <p>The sun is reportedly hot,<sup><a href="#note2112295062620ce2af0e040-2"><span id="noteref2112295062620ce2af0e040-1">1</span></a></sup> just like freshly baked potatoes.<sup><a href="#note2112295062620ce2af0e040-2"><span id="noteref2112295062620ce2af0e040-3">1</span></a></sup> Ice is cold.<sup><a href="#note2112295062620ce2af0e040-5"><span id="noteref2112295062620ce2af0e040-4">2</span></a></sup></p>
> 
> <ol>
> 	<li><sup><a href="#noteref2112295062620ce2af0e040-1">1</a></sup> <sup><a href="#noteref2112295062620ce2af0e040-3">2</a></sup><span id="note2112295062620ce2af0e040-2"> </span>Ouch. I also want this to contain a list: 
> <ul>
> <li>Item 1</li>
> </ul>
> </li>
> 	<li><sup><a href="#noteref2112295062620ce2af0e040-4">1</a></sup><span id="note2112295062620ce2af0e040-5"> </span>Brrr.</li>
> </ol>

I'm looking to achieve this type of output. Is such a thing possible?

**Comment by ikirudennis** [comment]
I'm not able to come up with a way to accomplish this using textile's syntax, but you can always fall back to raw HTML instead, though it isn't very pretty:

```
The sun is reportedly hot,[#hot] just like freshly baked potatoes.[#hot] Ice is cold.[#cold]

note#hot. Ouch. here's a list:<ul><li>Item 1</li></ul>

note#cold. Brrr.

notelist:1.
```

And you'll likely have to keep that `ul` and all `li`s on one line in order for it to properly handle it too.

I'd recommend raising this as an issue on the [textile spec repo](https://github.com/textile/textile-spec) and maybe something can get sorted out there.

I hope that helps

**Comment by AB1908** [comment]
Thanks for the update. Let me close and reopen it there.
